package sistema_registro;


import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author wianp
 */
public class Acceso_Pantallas extends javax.swing.JFrame {

    /**
     * Creates new form CheckBox
     */
    public Acceso_Pantallas() {
        initComponents();
    }
    
   
    
        public void addCheckbox (int column, JTable Tabla_Seccion){
        
        TableColumn tc = Tabla_Seccion.getColumnModel().getColumn(column);
        tc.setCellEditor(Tabla_Seccion.getDefaultEditor(Boolean.class));
        tc.setCellEditor((TableCellEditor) Tabla_Seccion.getDefaultRenderer(Boolean.class));
        
    }
    
    public boolean IsSelected(int row, int column, JTable Tabla_Seccion){
        
        return Tabla_Seccion.getValueAt( row, column) != null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        chb_Empleados = new javax.swing.JCheckBox();
        chb_Notas = new javax.swing.JCheckBox();
        chb_Periodo = new javax.swing.JCheckBox();
        chb_Aula = new javax.swing.JCheckBox();
        chb_Secciones = new javax.swing.JCheckBox();
        chb_Carrera = new javax.swing.JCheckBox();
        chb_Asignatura = new javax.swing.JCheckBox();
        chb_Alumno = new javax.swing.JCheckBox();
        chb_Matricula = new javax.swing.JCheckBox();
        chb_CancelarAsignatura = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        fechaHoy1 = new javax.swing.JLabel();
        fechaHoy = new javax.swing.JLabel();
        cbo_NombreUsuario = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        chb_EmpleadosG = new javax.swing.JCheckBox();
        chb_EmpleadosB = new javax.swing.JCheckBox();
        chb_EmpleadosA = new javax.swing.JCheckBox();
        chb_EmpleadosE = new javax.swing.JCheckBox();
        chb_PeriodoG = new javax.swing.JCheckBox();
        chb_PeriodoA = new javax.swing.JCheckBox();
        chb_PeriodoB = new javax.swing.JCheckBox();
        chb_PeriodoE = new javax.swing.JCheckBox();
        chb_SeccionesG = new javax.swing.JCheckBox();
        chb_SeccionesA = new javax.swing.JCheckBox();
        chb_SeccionesB = new javax.swing.JCheckBox();
        chb_SeccionesE = new javax.swing.JCheckBox();
        chb_AsignaturaG = new javax.swing.JCheckBox();
        chb_MatriculaG = new javax.swing.JCheckBox();
        chb_NotasG = new javax.swing.JCheckBox();
        chb_AsignaturaA = new javax.swing.JCheckBox();
        chb_MatriculaA = new javax.swing.JCheckBox();
        chb_NotasA = new javax.swing.JCheckBox();
        chb_AsignaturaB = new javax.swing.JCheckBox();
        chb_MatriculaB = new javax.swing.JCheckBox();
        chb_NotasB = new javax.swing.JCheckBox();
        chb_AsignaturaE = new javax.swing.JCheckBox();
        chb_MatriculaE = new javax.swing.JCheckBox();
        chb_NotasE = new javax.swing.JCheckBox();
        chb_AulaG = new javax.swing.JCheckBox();
        chb_CarreraG = new javax.swing.JCheckBox();
        chb_AlumnoG = new javax.swing.JCheckBox();
        chb_AulaA = new javax.swing.JCheckBox();
        chb_CarreraA = new javax.swing.JCheckBox();
        chb_AlumnoA = new javax.swing.JCheckBox();
        chb_AulaB = new javax.swing.JCheckBox();
        chb_CarreraB = new javax.swing.JCheckBox();
        chb_AlumnoB = new javax.swing.JCheckBox();
        chb_AulaE = new javax.swing.JCheckBox();
        chb_CarreraE = new javax.swing.JCheckBox();
        chb_AlumnoE = new javax.swing.JCheckBox();
        chb_CancelarAsignaturaG = new javax.swing.JCheckBox();
        chb_CancelarAsignaturaA = new javax.swing.JCheckBox();
        chb_CancelarAsignaturaB = new javax.swing.JCheckBox();
        chb_CancelarAsignaturaE = new javax.swing.JCheckBox();
        lbl_Empleados = new javax.swing.JLabel();
        lbl_Periodo = new javax.swing.JLabel();
        lbl_Secciones = new javax.swing.JLabel();
        lbl_Asignatura = new javax.swing.JLabel();
        lbl_Matricula = new javax.swing.JLabel();
        lbl_CancelarAsignatura = new javax.swing.JLabel();
        lbl_Alumno = new javax.swing.JLabel();
        lbl_Carrera = new javax.swing.JLabel();
        lbl_Aula = new javax.swing.JLabel();
        lbl_Notas = new javax.swing.JLabel();
        btn_Limpiar = new javax.swing.JButton();
        btn_Guardar = new javax.swing.JButton();
        lbl_usuario = new javax.swing.JLabel();
        iconodeUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Permisos de Pantallas "));

        chb_Empleados.setText("Empleados");

        chb_Notas.setText("Notas");

        chb_Periodo.setText("Periodo");

        chb_Aula.setText("Aula");

        chb_Secciones.setText("Secciones");

        chb_Carrera.setText("Carrera");

        chb_Asignatura.setText("Asignatura");

        chb_Alumno.setText("Alumno");

        chb_Matricula.setText("Matricula");

        chb_CancelarAsignatura.setText("CancelarAsignatura");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chb_Empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chb_Notas, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chb_Periodo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chb_Aula, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chb_Secciones, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chb_Carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chb_Asignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chb_Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chb_Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addComponent(chb_CancelarAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chb_Matricula)
                        .addGap(18, 18, 18)
                        .addComponent(chb_CancelarAsignatura))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(chb_Asignatura)
                            .addGap(18, 18, 18)
                            .addComponent(chb_Alumno))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chb_Secciones)
                                .addGap(18, 18, 18)
                                .addComponent(chb_Carrera))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chb_Periodo)
                                .addGap(18, 18, 18)
                                .addComponent(chb_Aula))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chb_Empleados)
                                .addGap(18, 18, 18)
                                .addComponent(chb_Notas)))))
                .addGap(15, 15, 15))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Usuario:");

        fechaHoy1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fechaHoy1.setText("      Fecha:");

        fechaHoy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fechaHoy.setText("Fecha hoy");

        cbo_NombreUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el nombre usuario:" }));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Permisos de Funcionalidad"));

        chb_EmpleadosG.setText("Guardar");
        chb_EmpleadosG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_EmpleadosGActionPerformed(evt);
            }
        });

        chb_EmpleadosB.setText("Buscar");
        chb_EmpleadosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_EmpleadosBActionPerformed(evt);
            }
        });

        chb_EmpleadosA.setText("Actualizar");
        chb_EmpleadosA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_EmpleadosAActionPerformed(evt);
            }
        });

        chb_EmpleadosE.setText("Eliminar");
        chb_EmpleadosE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_EmpleadosEActionPerformed(evt);
            }
        });

        chb_PeriodoG.setText("Guardar");
        chb_PeriodoG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_PeriodoGActionPerformed(evt);
            }
        });

        chb_PeriodoA.setText("Actualizar");
        chb_PeriodoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_PeriodoAActionPerformed(evt);
            }
        });

        chb_PeriodoB.setText("Buscar");
        chb_PeriodoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_PeriodoBActionPerformed(evt);
            }
        });

        chb_PeriodoE.setText("Eliminar");
        chb_PeriodoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_PeriodoEActionPerformed(evt);
            }
        });

        chb_SeccionesG.setText("Guardar");
        chb_SeccionesG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_SeccionesGActionPerformed(evt);
            }
        });

        chb_SeccionesA.setText("Actualizar");
        chb_SeccionesA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_SeccionesAActionPerformed(evt);
            }
        });

        chb_SeccionesB.setText("Buscar");
        chb_SeccionesB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_SeccionesBActionPerformed(evt);
            }
        });

        chb_SeccionesE.setText("Eliminar");
        chb_SeccionesE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_SeccionesEActionPerformed(evt);
            }
        });

        chb_AsignaturaG.setText("Guardar");
        chb_AsignaturaG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_AsignaturaGActionPerformed(evt);
            }
        });

        chb_MatriculaG.setText("Guardar");
        chb_MatriculaG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_MatriculaGActionPerformed(evt);
            }
        });

        chb_NotasG.setText("Guardar");
        chb_NotasG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_NotasGActionPerformed(evt);
            }
        });

        chb_AsignaturaA.setText("Actualizar");
        chb_AsignaturaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_AsignaturaAActionPerformed(evt);
            }
        });

        chb_MatriculaA.setText("Actualizar");
        chb_MatriculaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_MatriculaAActionPerformed(evt);
            }
        });

        chb_NotasA.setText("Actualizar");
        chb_NotasA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_NotasAActionPerformed(evt);
            }
        });

        chb_AsignaturaB.setText("Buscar");
        chb_AsignaturaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_AsignaturaBActionPerformed(evt);
            }
        });

        chb_MatriculaB.setText("Buscar");
        chb_MatriculaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_MatriculaBActionPerformed(evt);
            }
        });

        chb_NotasB.setText("Buscar");
        chb_NotasB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_NotasBActionPerformed(evt);
            }
        });

        chb_AsignaturaE.setText("Eliminar");
        chb_AsignaturaE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_AsignaturaEActionPerformed(evt);
            }
        });

        chb_MatriculaE.setText("Eliminar");
        chb_MatriculaE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_MatriculaEActionPerformed(evt);
            }
        });

        chb_NotasE.setText("Eliminar");
        chb_NotasE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_NotasEActionPerformed(evt);
            }
        });

        chb_AulaG.setText("Guardar");
        chb_AulaG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_AulaGActionPerformed(evt);
            }
        });

        chb_CarreraG.setText("Guardar");
        chb_CarreraG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_CarreraGActionPerformed(evt);
            }
        });

        chb_AlumnoG.setText("Guardar");
        chb_AlumnoG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_AlumnoGActionPerformed(evt);
            }
        });

        chb_AulaA.setText("Actualizar");
        chb_AulaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_AulaAActionPerformed(evt);
            }
        });

        chb_CarreraA.setText("Actualizar");
        chb_CarreraA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_CarreraAActionPerformed(evt);
            }
        });

        chb_AlumnoA.setText("Actualizar");
        chb_AlumnoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_AlumnoAActionPerformed(evt);
            }
        });

        chb_AulaB.setText("Buscar");
        chb_AulaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_AulaBActionPerformed(evt);
            }
        });

        chb_CarreraB.setText("Buscar");
        chb_CarreraB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_CarreraBActionPerformed(evt);
            }
        });

        chb_AlumnoB.setText("Buscar");
        chb_AlumnoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_AlumnoBActionPerformed(evt);
            }
        });

        chb_AulaE.setText("Eliminar");
        chb_AulaE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_AulaEActionPerformed(evt);
            }
        });

        chb_CarreraE.setText("Eliminar");
        chb_CarreraE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_CarreraEActionPerformed(evt);
            }
        });

        chb_AlumnoE.setText("Eliminar");
        chb_AlumnoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_AlumnoEActionPerformed(evt);
            }
        });

        chb_CancelarAsignaturaG.setText("Guardar");
        chb_CancelarAsignaturaG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_CancelarAsignaturaGActionPerformed(evt);
            }
        });

        chb_CancelarAsignaturaA.setText("Actualizar");
        chb_CancelarAsignaturaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_CancelarAsignaturaAActionPerformed(evt);
            }
        });

        chb_CancelarAsignaturaB.setText("Buscar");
        chb_CancelarAsignaturaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_CancelarAsignaturaBActionPerformed(evt);
            }
        });

        chb_CancelarAsignaturaE.setText("Eliminar");
        chb_CancelarAsignaturaE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_CancelarAsignaturaEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(chb_CancelarAsignaturaG, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(chb_CancelarAsignaturaA, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(chb_CancelarAsignaturaB, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(chb_CancelarAsignaturaE, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chb_AlumnoG, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(chb_AlumnoA, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chb_CarreraG, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(chb_CarreraA, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chb_AulaG, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(chb_AulaA, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chb_AlumnoB, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(chb_AlumnoE, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chb_CarreraB, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(chb_CarreraE, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chb_AulaB, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(chb_AulaE, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chb_NotasG, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(chb_NotasA, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chb_MatriculaG, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(chb_MatriculaA, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chb_AsignaturaG, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(chb_AsignaturaA, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chb_NotasB, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(chb_NotasE, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chb_MatriculaB, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(chb_MatriculaE, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chb_AsignaturaB, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(chb_AsignaturaE, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chb_SeccionesG, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(chb_SeccionesA, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chb_PeriodoG, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(chb_PeriodoA, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chb_EmpleadosG, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(chb_EmpleadosA, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chb_SeccionesB, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(chb_SeccionesE, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chb_PeriodoB, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(chb_PeriodoE, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chb_EmpleadosB, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(chb_EmpleadosE, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chb_EmpleadosE)
                    .addComponent(chb_EmpleadosB)
                    .addComponent(chb_EmpleadosA)
                    .addComponent(chb_EmpleadosG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chb_PeriodoE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chb_PeriodoB)
                        .addComponent(chb_PeriodoA)
                        .addComponent(chb_PeriodoG)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chb_SeccionesE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chb_SeccionesB)
                        .addComponent(chb_SeccionesA)
                        .addComponent(chb_SeccionesG)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chb_AsignaturaE)
                    .addComponent(chb_AsignaturaB)
                    .addComponent(chb_AsignaturaA)
                    .addComponent(chb_AsignaturaG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chb_MatriculaE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chb_MatriculaB)
                        .addComponent(chb_MatriculaA)
                        .addComponent(chb_MatriculaG)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chb_NotasE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chb_NotasB)
                        .addComponent(chb_NotasA)
                        .addComponent(chb_NotasG)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chb_AulaE)
                    .addComponent(chb_AulaB)
                    .addComponent(chb_AulaA)
                    .addComponent(chb_AulaG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chb_CarreraE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chb_CarreraB)
                        .addComponent(chb_CarreraA)
                        .addComponent(chb_CarreraG)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chb_AlumnoE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chb_AlumnoB)
                        .addComponent(chb_AlumnoA)
                        .addComponent(chb_AlumnoG)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chb_CancelarAsignaturaE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chb_CancelarAsignaturaB)
                        .addComponent(chb_CancelarAsignaturaA)
                        .addComponent(chb_CancelarAsignaturaG)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_Empleados.setText("Empleados");

        lbl_Periodo.setText("Periodo");

        lbl_Secciones.setText("Secciones");

        lbl_Asignatura.setText("Asignatura");

        lbl_Matricula.setText("Matricula");

        lbl_CancelarAsignatura.setText("Cancelar Asignatura");

        lbl_Alumno.setText("Alumno");

        lbl_Carrera.setText("Carrera");

        lbl_Aula.setText("Aula");

        lbl_Notas.setText("Notas");

        btn_Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botton_Limpiar.png"))); // NOI18N
        btn_Limpiar.setText("Limpiar");

        btn_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botton_Guardar.png"))); // NOI18N
        btn_Guardar.setText("Guardar");

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_usuario.setText("Nombre Usuario");

        iconodeUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/User.png"))); // NOI18N

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu.png"))); // NOI18N
        jMenu1.setText("Menu");

        jMenu2.setText("jMenu2");
        jMenu1.add(jMenu2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(iconodeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(38, 38, 38)
                                .addComponent(cbo_NombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(278, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fechaHoy1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaHoy, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(btn_Limpiar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Guardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_Carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_Empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_Periodo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_Secciones, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_Notas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_Aula, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_Asignatura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_Matricula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(38, 38, 38))
                                    .addComponent(lbl_CancelarAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconodeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fechaHoy1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaHoy, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(lbl_usuario)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbo_NombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_Empleados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_Periodo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_Secciones)
                        .addGap(14, 14, 14)
                        .addComponent(lbl_Asignatura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_Matricula)
                        .addGap(11, 11, 11)
                        .addComponent(lbl_Notas)
                        .addGap(13, 13, 13)
                        .addComponent(lbl_Aula)
                        .addGap(13, 13, 13)
                        .addComponent(lbl_Carrera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_Alumno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_CancelarAsignatura)
                        .addGap(81, 81, 81))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Limpiar)
                            .addComponent(btn_Guardar))
                        .addContainerGap())))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox_ViernesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_ViernesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_ViernesActionPerformed

    private void jCheckBox_JuevesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_JuevesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_JuevesActionPerformed

    private void btn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AceptarActionPerformed
        
        
    }//GEN-LAST:event_btn_AceptarActionPerformed

    private void chb_EmpleadosGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_EmpleadosGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_EmpleadosGActionPerformed

    private void chb_EmpleadosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_EmpleadosBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_EmpleadosBActionPerformed

    private void chb_EmpleadosAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_EmpleadosAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_EmpleadosAActionPerformed

    private void chb_EmpleadosEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_EmpleadosEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_EmpleadosEActionPerformed

    private void chb_PeriodoGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_PeriodoGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_PeriodoGActionPerformed

    private void chb_PeriodoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_PeriodoAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_PeriodoAActionPerformed

    private void chb_PeriodoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_PeriodoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_PeriodoBActionPerformed

    private void chb_PeriodoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_PeriodoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_PeriodoEActionPerformed

    private void chb_SeccionesGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_SeccionesGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_SeccionesGActionPerformed

    private void chb_SeccionesAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_SeccionesAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_SeccionesAActionPerformed

    private void chb_SeccionesBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_SeccionesBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_SeccionesBActionPerformed

    private void chb_SeccionesEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_SeccionesEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_SeccionesEActionPerformed

    private void chb_AsignaturaGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_AsignaturaGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_AsignaturaGActionPerformed

    private void chb_MatriculaGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_MatriculaGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_MatriculaGActionPerformed

    private void chb_NotasGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_NotasGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_NotasGActionPerformed

    private void chb_AsignaturaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_AsignaturaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_AsignaturaAActionPerformed

    private void chb_MatriculaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_MatriculaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_MatriculaAActionPerformed

    private void chb_NotasAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_NotasAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_NotasAActionPerformed

    private void chb_AsignaturaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_AsignaturaBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_AsignaturaBActionPerformed

    private void chb_MatriculaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_MatriculaBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_MatriculaBActionPerformed

    private void chb_NotasBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_NotasBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_NotasBActionPerformed

    private void chb_AsignaturaEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_AsignaturaEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_AsignaturaEActionPerformed

    private void chb_MatriculaEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_MatriculaEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_MatriculaEActionPerformed

    private void chb_NotasEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_NotasEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_NotasEActionPerformed

    private void chb_AulaGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_AulaGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_AulaGActionPerformed

    private void chb_CarreraGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_CarreraGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_CarreraGActionPerformed

    private void chb_AlumnoGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_AlumnoGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_AlumnoGActionPerformed

    private void chb_AulaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_AulaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_AulaAActionPerformed

    private void chb_CarreraAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_CarreraAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_CarreraAActionPerformed

    private void chb_AlumnoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_AlumnoAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_AlumnoAActionPerformed

    private void chb_AulaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_AulaBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_AulaBActionPerformed

    private void chb_CarreraBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_CarreraBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_CarreraBActionPerformed

    private void chb_AlumnoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_AlumnoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_AlumnoBActionPerformed

    private void chb_AulaEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_AulaEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_AulaEActionPerformed

    private void chb_CarreraEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_CarreraEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_CarreraEActionPerformed

    private void chb_AlumnoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_AlumnoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_AlumnoEActionPerformed

    private void chb_CancelarAsignaturaGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_CancelarAsignaturaGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_CancelarAsignaturaGActionPerformed

    private void chb_CancelarAsignaturaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_CancelarAsignaturaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_CancelarAsignaturaAActionPerformed

    private void chb_CancelarAsignaturaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_CancelarAsignaturaBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_CancelarAsignaturaBActionPerformed

    private void chb_CancelarAsignaturaEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_CancelarAsignaturaEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_CancelarAsignaturaEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceso_Pantallas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceso_Pantallas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceso_Pantallas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceso_Pantallas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceso_Pantallas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JButton btn_Limpiar;
    private javax.swing.JComboBox<String> cbo_NombreUsuario;
    private javax.swing.JCheckBox chb_Alumno;
    private javax.swing.JCheckBox chb_AlumnoA;
    private javax.swing.JCheckBox chb_AlumnoB;
    private javax.swing.JCheckBox chb_AlumnoE;
    private javax.swing.JCheckBox chb_AlumnoG;
    private javax.swing.JCheckBox chb_Asignatura;
    private javax.swing.JCheckBox chb_AsignaturaA;
    private javax.swing.JCheckBox chb_AsignaturaB;
    private javax.swing.JCheckBox chb_AsignaturaE;
    private javax.swing.JCheckBox chb_AsignaturaG;
    private javax.swing.JCheckBox chb_Aula;
    private javax.swing.JCheckBox chb_AulaA;
    private javax.swing.JCheckBox chb_AulaB;
    private javax.swing.JCheckBox chb_AulaE;
    private javax.swing.JCheckBox chb_AulaG;
    private javax.swing.JCheckBox chb_CancelarAsignatura;
    private javax.swing.JCheckBox chb_CancelarAsignaturaA;
    private javax.swing.JCheckBox chb_CancelarAsignaturaB;
    private javax.swing.JCheckBox chb_CancelarAsignaturaE;
    private javax.swing.JCheckBox chb_CancelarAsignaturaG;
    private javax.swing.JCheckBox chb_Carrera;
    private javax.swing.JCheckBox chb_CarreraA;
    private javax.swing.JCheckBox chb_CarreraB;
    private javax.swing.JCheckBox chb_CarreraE;
    private javax.swing.JCheckBox chb_CarreraG;
    private javax.swing.JCheckBox chb_Empleados;
    private javax.swing.JCheckBox chb_EmpleadosA;
    private javax.swing.JCheckBox chb_EmpleadosB;
    private javax.swing.JCheckBox chb_EmpleadosE;
    private javax.swing.JCheckBox chb_EmpleadosG;
    private javax.swing.JCheckBox chb_Matricula;
    private javax.swing.JCheckBox chb_MatriculaA;
    private javax.swing.JCheckBox chb_MatriculaB;
    private javax.swing.JCheckBox chb_MatriculaE;
    private javax.swing.JCheckBox chb_MatriculaG;
    private javax.swing.JCheckBox chb_Notas;
    private javax.swing.JCheckBox chb_NotasA;
    private javax.swing.JCheckBox chb_NotasB;
    private javax.swing.JCheckBox chb_NotasE;
    private javax.swing.JCheckBox chb_NotasG;
    private javax.swing.JCheckBox chb_Periodo;
    private javax.swing.JCheckBox chb_PeriodoA;
    private javax.swing.JCheckBox chb_PeriodoB;
    private javax.swing.JCheckBox chb_PeriodoE;
    private javax.swing.JCheckBox chb_PeriodoG;
    private javax.swing.JCheckBox chb_Secciones;
    private javax.swing.JCheckBox chb_SeccionesA;
    private javax.swing.JCheckBox chb_SeccionesB;
    private javax.swing.JCheckBox chb_SeccionesE;
    private javax.swing.JCheckBox chb_SeccionesG;
    private javax.swing.JLabel fechaHoy;
    private javax.swing.JLabel fechaHoy1;
    private javax.swing.JLabel iconodeUsuario;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_Alumno;
    private javax.swing.JLabel lbl_Asignatura;
    private javax.swing.JLabel lbl_Aula;
    private javax.swing.JLabel lbl_CancelarAsignatura;
    private javax.swing.JLabel lbl_Carrera;
    private javax.swing.JLabel lbl_Empleados;
    private javax.swing.JLabel lbl_Matricula;
    private javax.swing.JLabel lbl_Notas;
    private javax.swing.JLabel lbl_Periodo;
    private javax.swing.JLabel lbl_Secciones;
    private javax.swing.JLabel lbl_usuario;
    // End of variables declaration//GEN-END:variables
}
