/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_registro;

import codigo.Conexion_consulta;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import sistema_registro.SQL.ConectorSQL;

/**
 *
 * @author William
 */
public class Asignaturas extends javax.swing.JFrame {

Connection con = null;
    String titulos [] = {"Codigo de Asignatura", "Nombre de la Asignatura", "Unidades Valorativas", "Id Carrera", "Requisito1", "Requisito2"};
   
    DefaultTableModel modelo =  new DefaultTableModel();
    Statement stmt = null;
    String var, var2;
/**
    /**
     * Creates new form Asignaturas
     */
    public Asignaturas() throws SQLException {
        this.con = ConectorSQL.obtenerConexion ();
        initComponents();
        ArrayList<String> lista = new ArrayList<String>();
             lista = new Conexion_consulta().llenar_combo2();
            for(int i = 0; i<lista.size();i++){
                cbo_IdCarrera.addItem(lista.get(i));
            }
             ArrayList<String> lista2 = new ArrayList<String>();
             lista2 = new Conexion_consulta().llenar_requisito();
            for(int i = 0; i<lista2.size();i++){
               cbo_Req1.addItem(lista2.get(i));
               cbo_Req2.addItem(lista2.get(i));
            }
            
            this.setTitle("Asignaturas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_RegistroAsignatura = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_AdmCarrera = new javax.swing.JButton();
        lbl_UniVal = new javax.swing.JLabel();
        lbl_IdCarrera = new javax.swing.JLabel();
        cbo_Req1 = new javax.swing.JComboBox<>();
        cbo_Req2 = new javax.swing.JComboBox<>();
        lbl_Req1 = new javax.swing.JLabel();
        lbl_Req2 = new javax.swing.JLabel();
        cbo_IdCarrera = new javax.swing.JComboBox<>();
        txt_UniVal = new javax.swing.JTextField();
        txt_NombreA = new javax.swing.JTextField();
        txt_codA = new javax.swing.JTextField();
        lbl_NombreA = new javax.swing.JLabel();
        lbl_codA = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        btn_eliminar1 = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_requisitos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabla_RegistroAsignatura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Asinatura", "Asignatura", "UV", "Id Carrera", "Requisito 1", "Requisito 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla_RegistroAsignatura.setToolTipText("Presiona consulta para ver todas las asignaturas\n");
        Tabla_RegistroAsignatura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_RegistroAsignaturaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla_RegistroAsignatura);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, 840, 106));

        jPanel1.setBackground(new java.awt.Color(232, 251, 249));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText(" Registro Asignatura");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(299, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(287, 287, 287))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, 70));

        jPanel2.setBackground(new java.awt.Color(215, 236, 233));

        btn_AdmCarrera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton_Agregar_pantallaAparte.png"))); // NOI18N
        btn_AdmCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AdmCarreraActionPerformed(evt);
            }
        });

        lbl_UniVal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_UniVal.setText("Unidad Valorativa:");

        lbl_IdCarrera.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_IdCarrera.setText("Carrera:");

        cbo_Req1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la asignatura1:" }));
        cbo_Req1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_Req1ActionPerformed(evt);
            }
        });

        cbo_Req2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la asignatura2:" }));
        cbo_Req2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_Req2ActionPerformed(evt);
            }
        });

        lbl_Req1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Req1.setText("Requisito 1:");

        lbl_Req2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Req2.setText("Requisito 2:");

        cbo_IdCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una carrera" }));

        txt_UniVal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_UniVal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_UniValKeyTyped(evt);
            }
        });

        txt_NombreA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_NombreA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NombreAKeyTyped(evt);
            }
        });

        txt_codA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_codA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codAActionPerformed(evt);
            }
        });
        txt_codA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_codAKeyTyped(evt);
            }
        });

        lbl_NombreA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_NombreA.setText("Nombre de la Asigntura:");

        lbl_codA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_codA.setText("Codigo de la Asignatura:");

        btn_buscar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botton_Consulta.png"))); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buscarMouseClicked(evt);
            }
        });
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_eliminar1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_eliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botton_Eliminar.png"))); // NOI18N
        btn_eliminar1.setText("Eliminar");
        btn_eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar1ActionPerformed(evt);
            }
        });

        btn_actualizar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botton_Actualizar.png"))); // NOI18N
        btn_actualizar.setText("Actualizar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        btn_guardar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botton_Guardar.png"))); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_requisitos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_requisitos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/writing-on-an-open-book_icon-icons.com_70325.png"))); // NOI18N
        btn_requisitos.setText("Requisitos");
        btn_requisitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_requisitosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_requisitos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btn_eliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbl_codA)
                                .addGap(26, 26, 26))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_NombreA)
                                    .addComponent(lbl_UniVal))
                                .addGap(24, 24, 24)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_codA, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(txt_NombreA)
                            .addComponent(txt_UniVal))
                        .addGap(119, 119, 119))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_Req1)
                            .addComponent(lbl_Req2)
                            .addComponent(lbl_IdCarrera))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cbo_IdCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbo_Req1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbo_Req2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_AdmCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_codA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_codA))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_guardar)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_NombreA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_NombreA))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btn_actualizar)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_UniVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_UniVal))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lbl_IdCarrera)
                                .addGap(41, 41, 41))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbo_IdCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_AdmCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbo_Req1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Req1))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbo_Req2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Req2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_eliminar1)
                        .addGap(19, 19, 19)
                        .addComponent(btn_buscar)
                        .addGap(29, 29, 29)
                        .addComponent(btn_requisitos)))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 840, 480));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagen 3.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -1, 1240, 740));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton_retroceder.png"))); // NOI18N
        jMenu1.setText("Regresar");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicio.png"))); // NOI18N
        jMenuItem1.setText("Menu Principal");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
         actualizarDatos();
         
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        
        String nombreAsignatura = txt_NombreA.getText() + " ";
        if ((txt_codA.getText().equals("")) || (txt_NombreA.getText().equals("")) ||
            (cbo_IdCarrera.getSelectedItem().equals("Seleccione la asignatura"))) {

            javax.swing.JOptionPane.showMessageDialog(this,"¡Debe seleccionar la asignatura a actualizar! \n","¡AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            txt_NombreA.requestFocus();
            return;
        }
        else if(JOptionPane.showConfirmDialog(null, "¿Está seguro que desea actualizar el registro de asignatura" +nombreAsignatura + "?", "Confirmación de actualización", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE
        ) == JOptionPane.YES_OPTION) {
            String id_carrera = cbo_IdCarrera.getSelectedItem().toString().substring(0, 4);
            String requisito1 = cbo_Req1.getSelectedItem().toString().substring(0, 5);
            String requisito2 = cbo_Req2.getSelectedItem().toString().substring(0, 6);
            try {
                PreparedStatement ps;
                ResultSet rs;
                ps = con.prepareStatement("Update Requisito_Asignatura set"
                    + " RequisitoAsignatura = ? ,"
                    + " id_asignatura = ? , "
                    + " requisito1 = ? , "
                    + " requisito2 = ? "
                    + " where id_asignatura =\'"+txt_codA.getText()+"\'");
                  ps.setString(1, txt_codA.getText());
                  ps.setString(2, txt_NombreA.getText());
                  ps.setString(3, txt_UniVal.getText());
                  ps.setString(4, id_carrera);
                  ps.setString(5, requisito1);
                  ps.setString(6, requisito2);
               
                int res = ps.executeUpdate();
            } catch (Exception e) {
                System.out.println(e);
            }

        
        }
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        
        String cadena1, cadena2, cadena3, cadena4, cadena5, cadena6;
        cadena1 = txt_codA.getText();
        cadena2 = txt_NombreA.getText();
        cadena3 = txt_UniVal.getText();
        String id_carrera = cbo_IdCarrera.getSelectedItem().toString().substring(0, 4);
        String requisito1= cbo_Req1.getSelectedItem().toString().substring(0,5);
        String requisito2= cbo_Req2.getSelectedItem().toString().substring(0,6);
  

        if ((txt_codA.getText().equals("")) || (txt_NombreA.getText().equals(""))  || (txt_UniVal.getText().equals(""))  
                ||  (cbo_IdCarrera.getSelectedItem().equals("Seleccione una asignatura")) 
               //||  (cbo_Req1.getSelectedItem().equals("Seleccione un asignatura")) 
                ) {

            javax.swing.JOptionPane.showMessageDialog(this,"¡Debe llenar todos los campos! \n","¡AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            txt_codA.requestFocus();
            return;
        }

        if(existeAsignatura()){
            return;
        }

        if(!validarLongitud(txt_codA,3)){
            JOptionPane.showMessageDialog(null, "El codigo de asignaturas tiene que ser minimo de 3 caracteres", "Longitud de codigo de asignatura", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        if(!validarLongitud(txt_NombreA,7)){
            JOptionPane.showMessageDialog(null, "El Nombre de la asignatura es muy corto el mínimo es de 7 caracteres", "Longitud del nombre de asignatura", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
       
         if(!validarLongitud(txt_UniVal,1)){
            JOptionPane.showMessageDialog(null, "La unidades valorativas debe ser de un mínimo de 1 caracter", "Longitud de las unidades valorativas", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
         
        

        try{
            PreparedStatement ps;
            ResultSet rs;

            ps=con.prepareStatement("Insert into Asignaturas (cod_asignaturas, nombre_asignaturas, UV, id_carrera, requisito1, requisito2 )"
                + "                VALUES(?,?,?,?,?,?)");
            ps.setString(1, txt_codA.getText());
            ps.setString(2, txt_NombreA.getText());
            ps.setString(3, txt_UniVal.getText());
            ps.setString(4, id_carrera);
            ps.setString(5, requisito1);
            ps.setString(6, requisito2);
            
            int res= ps.executeUpdate(); 
            JOptionPane.showMessageDialog(null, "Se ha guardado la información en Registro de Asignatura");
             } catch ( Exception e) {
            System.out.println(e);
        
             JOptionPane.showMessageDialog(null, e.getMessage());
        }
        

        actualizarDatos();
        LimpiarCajas();
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar1ActionPerformed
          String Asignatura = txt_NombreA.getText() + " " + txt_codA.getText();
          
           if ((txt_NombreA.getText().equals("")) || (txt_codA.getText().equals(""))  || (txt_UniVal.getText().equals(""))  ) {

            javax.swing.JOptionPane.showMessageDialog(this,"¡Debe seleccionar la asignatura que desea eliminar! \n","¡AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
           
        }
          else if (JOptionPane.showConfirmDialog(null, "¿Está seguro que desea eliminar el registro de asignatura " + Asignatura + "", "Confirmación de eliminación",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE
        ) == JOptionPane.YES_OPTION) {

            try {
                Statement st2 = con.createStatement();
                String sql = "Delete Asignaturas "
                + "where cod_asignaturas = (Select cod_asignaturas from Asignaturas where nombre_asignaturas = '"+txt_NombreA.getText()+"')";

                int rs2 = st2.executeUpdate(sql);
                System.out.println(rs2);
                if(rs2 > 0){
                    JOptionPane.showMessageDialog(null, "Se ha borrado la información de la asignatura " + Asignatura + " correctamente");

                }else {
                    JOptionPane.showMessageDialog(null, "¡Error al eliminar la información!");

                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

        }
        actualizarDatos();
        LimpiarCajas();
    }//GEN-LAST:event_btn_eliminar1ActionPerformed

    private void btn_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarMouseClicked
        rellenar();
        this.jScrollPane1.setEnabled(true);
        this.Tabla_RegistroAsignatura.setEnabled(true);
    }//GEN-LAST:event_btn_buscarMouseClicked

    private void btn_AdmCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AdmCarreraActionPerformed
        Carrera cc = null;
        try {
            cc = new Carrera();
        } catch (SQLException ex) {
            Logger.getLogger(Carrera.class.getName()).log(Level.SEVERE, null, ex);
        }
        cc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_AdmCarreraActionPerformed

    private void Tabla_RegistroAsignaturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_RegistroAsignaturaMouseClicked
        if(Tabla_RegistroAsignatura.getSelectedRow () >= 0){
            llenarCampos();
        }
    }//GEN-LAST:event_Tabla_RegistroAsignaturaMouseClicked

    private void txt_codAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codAActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         this.dispose();
        Principal pa = null;
         try {
             pa = new Principal();
         } catch (SQLException ex) {
             Logger.getLogger(Carrera.class.getName()).log(Level.SEVERE, null, ex);
         }
        pa.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void cbo_Req2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_Req2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_Req2ActionPerformed

    private void cbo_Req1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_Req1ActionPerformed
      if(cbo_Req1.getSelectedItem().toString().length()==0){
     System.out.println("No hay texto");
    }

    }//GEN-LAST:event_cbo_Req1ActionPerformed

    private void btn_requisitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_requisitosActionPerformed
        
        this.dispose();
        RequisitoAsignatura req = null;
    try {
        req = new RequisitoAsignatura();
    } catch (SQLException ex) {
        Logger.getLogger(Asignaturas.class.getName()).log(Level.SEVERE, null, ex);
    }
        req.setVisible(true);
        
    }//GEN-LAST:event_btn_requisitosActionPerformed

    private void txt_codAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codAKeyTyped
       if (txt_codA.getText().length() >= 6) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Número máximo de caracteres admitidos");
        }
        if (evt.getKeyChar() == 8 || evt.getKeyChar() == 127
            || evt.getKeyChar() == 0 || evt.getKeyChar() == 3 || evt.getKeyChar() == 22
            || evt.getKeyChar() == 26 || evt.getKeyChar() == 24) {
            return;
        }
        char a = evt.getKeyChar();
        if (!Character.isLetterOrDigit(a)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Sólo letras y numeros");
        }
    }//GEN-LAST:event_txt_codAKeyTyped

    private void txt_NombreAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NombreAKeyTyped
        if (txt_NombreA.getText().length() >= 50) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Número máximo de caracteres admitidos");
        }
        if (evt.getKeyChar() == 8 || evt.getKeyChar() == 127
            || evt.getKeyChar() == 0 || evt.getKeyChar() == 3 || evt.getKeyChar() == 22
            || evt.getKeyChar() == 32 || evt.getKeyChar() == 26 || evt.getKeyChar() == 24) {
            return;
        }
        char a = evt.getKeyChar();
        if (Character.isDigit(a)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Sólo letras");
        }
    }//GEN-LAST:event_txt_NombreAKeyTyped

    private void txt_UniValKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_UniValKeyTyped
        char a=evt.getKeyChar();
            if (evt.getKeyChar() == 8 || evt.getKeyChar() == 127 || 
                 evt.getKeyChar() == 0 || evt.getKeyChar() == 3 || evt.getKeyChar() == 22 
                 || evt.getKeyChar() == 26 || evt.getKeyChar() == 24) {
        return;
        }
        if(txt_UniVal.getText().length() >=1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Número máximo de dígitos admitidos");
        }
        if(Character.isLetter(a) || !Character.isLetterOrDigit(a)){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Solo números");
        }
    }//GEN-LAST:event_txt_UniValKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asignaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asignaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asignaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asignaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Asignaturas().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Asignaturas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla_RegistroAsignatura;
    private javax.swing.JButton btn_AdmCarrera;
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_eliminar1;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_requisitos;
    private javax.swing.JComboBox<String> cbo_IdCarrera;
    private javax.swing.JComboBox<String> cbo_Req1;
    private javax.swing.JComboBox<String> cbo_Req2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_IdCarrera;
    private javax.swing.JLabel lbl_NombreA;
    private javax.swing.JLabel lbl_Req1;
    private javax.swing.JLabel lbl_Req2;
    private javax.swing.JLabel lbl_UniVal;
    private javax.swing.JLabel lbl_codA;
    private javax.swing.JTextField txt_NombreA;
    private javax.swing.JTextField txt_UniVal;
    private javax.swing.JTextField txt_codA;
    // End of variables declaration//GEN-END:variables


public boolean existeAsignatura(){
        try {
            Statement st = con.createStatement();
            String sql = "Select cod_asignaturas from Asignaturas where cod_asignaturas = '"+txt_codA.getText()+"'";
            ResultSet rs = st.executeQuery(sql);
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Ya existe esta Asignatura: "+txt_codA.getText()+" ", "Codigo de asignatura ¡Ya existe!", JOptionPane.INFORMATION_MESSAGE);
                return true;
            }
            else{
                return false;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Empleado.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }
       
           private boolean validarLongitud(JTextField texto, int longitud){
       if(texto.getText().length() >= longitud){
           return true;
       }
       else{
           return false;
       }
    }
         
 public void actualizarDatos(){
        try {
               
               String sql = "SELECT * FROM Asignaturas";
               stmt = con.createStatement();
               ResultSet rs = stmt.executeQuery(sql);
               modelo = new DefaultTableModel(null, titulos);
               Tabla_RegistroAsignatura.setModel(modelo);
                 while(rs.next()) {
                     
                          String []datos= new String[6];
                      datos[0] =rs.getString("cod_asignaturas");
                      datos[1] =rs.getString("nombre_asignaturas");
                      datos[2] =rs.getString("UV");
                      datos[3] =rs.getString("id_carrera");
                      datos[4] =rs.getString("requisito1");
                      datos[5] =rs.getString("requisito2");
                      
                     modelo.addRow(datos);
                      
                      centrar_datos();
                 }
            TableColumn TaRA = Tabla_RegistroAsignatura.getColumn(titulos[0]);
            TaRA.setMaxWidth(125);
            TableColumn cRA= Tabla_RegistroAsignatura.getColumn(titulos[1]);
            cRA.setMaxWidth(165);
            TableColumn UV= Tabla_RegistroAsignatura.getColumn(titulos[2]);
            UV.setMaxWidth(125);            
            TableColumn idC= Tabla_RegistroAsignatura.getColumn(titulos[3]);
           idC.setMaxWidth(165);
           TableColumn req1C= Tabla_RegistroAsignatura.getColumn(titulos[4]);
           req1C.setMaxWidth(165);
            TableColumn req2C= Tabla_RegistroAsignatura.getColumn(titulos[5]);
           req2C.setMaxWidth(165);
        }
        catch (Exception e) {
           
            System.err.println(e);
        }
           }
           
     public void centrar_datos() {
 
        DefaultTableCellRenderer modelocentrar = new DefaultTableCellRenderer();
        modelocentrar.setHorizontalAlignment(SwingConstants.CENTER);
         for (int i = 0; i <modelo.getRowCount(); i++) {
              Tabla_RegistroAsignatura.getColumnModel().getColumn(i).setCellRenderer(modelocentrar);
             
         }
     
    }
     
    
             
    
       private void rellenar(){
      try {
                    String cap = "";
                    ResultSet rs2 = null;
                   var = JOptionPane.showInputDialog(this, "Ingrese el nombre de la asignatura que desea consultar", "Consulta de facultad", JOptionPane.QUESTION_MESSAGE);
                    if (var == null) {
                        JOptionPane.showMessageDialog(this, "La acción fue cancelada", "¡AVISO!", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        if (var.equals("")) {
                            JOptionPane.showMessageDialog(this, "Favor de ingresar el nombre de la asignatura \n que desea consultar", "¡AVISO!", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            String sql = "SELECT * FROM Asignaturas where cod_asignaturas='"+var+"' or nombre_asignaturas ='"+var+"'";
                            stmt = con.createStatement();
                            rs2 = stmt.executeQuery(sql);

                            if (rs2.next()) {
                                txt_codA.setText(rs2.getString("cod_asignaturas"));
                                txt_NombreA.setText(rs2.getString("nombre_asignaturas"));
                                txt_UniVal.setText(rs2.getString("UV"));
                                
                            } else {
                                JOptionPane.showMessageDialog(null, "¡No se encuentra los datos: "+var+" ! Por favor verifique sí, lo escribio correctamente");
                            }
                        }

                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
    
    }

    private void LimpiarCajas() {
       
        txt_NombreA.setText(null);
        txt_UniVal.setText(null);
        txt_codA.setText(null);
        cbo_IdCarrera.setSelectedIndex(0);
        cbo_Req1.setSelectedIndex(0);
        cbo_Req2.setSelectedIndex(0);
       
    }

    private void llenarCampos() {
      int i = Tabla_RegistroAsignatura.getSelectedRow();
        txt_codA.setText(Tabla_RegistroAsignatura.getValueAt(i, 0).toString());
        txt_NombreA.setText(Tabla_RegistroAsignatura.getValueAt(i, 1).toString());
        txt_UniVal.setText(Tabla_RegistroAsignatura.getValueAt(i, 2).toString());
        cbo_IdCarrera.setSelectedItem(Tabla_RegistroAsignatura.getValueAt(i, 3).toString());
        cbo_Req1.setSelectedItem(Tabla_RegistroAsignatura.getValueAt(i, 4).toString());
        cbo_Req2.setSelectedItem(Tabla_RegistroAsignatura.getValueAt(i, 5).toString());

    }
  


}
