
package sistema_registro;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import sistema_registro.SQL.ConectorSQL;

/**
 *
 * @author wianp
 */
public class ConsultasEmpleados extends javax.swing.JFrame {

 Connection con = null;
   Statement stmt = null;
   String titulos[] = {"id","Nombres","Apellidos", "Campus","Telefono", "Password","Tipo usuario"};
   String fila[] = new String [7];
   DefaultTableModel modelo;

   
    public ConsultasEmpleados()  throws SQLException {
        this.con = ConectorSQL.obtenerConexion();
        initComponents();
        this.setTitle("Consulta Empleados");
        this.setLocation(335,200);
        this.setResizable(false);
     
  
               stmt = con.createStatement();
               ResultSet rs = stmt.executeQuery("select* from Empleados");
               
               modelo = new DefaultTableModel(null,titulos);
            
               while(rs.next()) {
                   
                   fila[0] = rs.getString("id");
                   fila[1] = rs.getString("Nombres");
                   fila[1] = rs.getString("Apellidos");
                   fila[2] = rs.getString("Campus");
                   fila[3] = rs.getString("Telefono");
                   fila[5] = rs.getString("Password");
                   fila[6] = rs.getString("Tipo Usuario");
                   
                   modelo.addRow(fila);     
               }
               Tabla_Empleados.setModel(modelo);
                TableColumn ci = Tabla_Empleados.getColumn("id");
                ci.setMaxWidth(25);
                TableColumn cn = Tabla_Empleados.getColumn("Nombre");
                cn.setMaxWidth(165);
                TableColumn cd = Tabla_Empleados.getColumn("Domicilio");
                cd.setMaxWidth(160);
                TableColumn ct = Tabla_Empleados.getColumn("Telefono");
                ct.setMaxWidth(90);
                TableColumn cp = Tabla_Empleados.getColumn("Password");
                cp.setMaxWidth(72);
                TableColumn ctipo = Tabla_Empleados.getColumn("Tipo Usuario");
                ctipo.setMaxWidth(95);
               
            }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Empleados = new javax.swing.JTable();
        BarraMenu = new javax.swing.JMenuBar();
        MenuArchivo = new javax.swing.JMenu();
        MenuRegistro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tabla_Empleados.setBackground(new java.awt.Color(204, 204, 204));
        Tabla_Empleados.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder()));
        Tabla_Empleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla_Empleados);

        MenuArchivo.setText("Archivo");

        MenuRegistro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        MenuRegistro.setText("Registro Empleados");
        MenuRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRegistroActionPerformed(evt);
            }
        });
        MenuArchivo.add(MenuRegistro);

        BarraMenu.add(MenuArchivo);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRegistroActionPerformed

        this.dispose();
        ConsultasEmpleados consultasEmpleados = null;
     try {
         consultasEmpleados = new ConsultasEmpleados();
     } catch (SQLException ex) {
         Logger.getLogger(ConsultasEmpleados.class.getName()).log(Level.SEVERE, null, ex);
     }
        consultasEmpleados.setVisible(true);
        Empleado E = null;
     try {
         E = new Empleado();
     } catch (SQLException ex) {
         Logger.getLogger(ConsultasEmpleados.class.getName()).log(Level.SEVERE, null, ex);
     }
        
        E.setVisible(true);
        
    }//GEN-LAST:event_MenuRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultasEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultasEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultasEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultasEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JMenu MenuArchivo;
    private javax.swing.JMenuItem MenuRegistro;
    private javax.swing.JTable Tabla_Empleados;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

  
}
