/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_registro;

import codigo.Conexion_consulta;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sistema_registro.SQL.ConectorSQL;

/**
 *
 * @author Mitsuki
 */
public class PeriodoHis extends javax.swing.JFrame {
Connection con;


    /**
     * Creates new form PeriodoHis
     */
    public PeriodoHis() throws SQLException {
        this.con = ConectorSQL.obtenerConexion();
        initComponents();
          ArrayList<String> lista = new ArrayList<String>();
             lista = new Conexion_consulta().llenar_period();
            for(int i = 0; i<lista.size();i++){
                cbo_periodo.addItem(lista.get(i));
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_periodo = new javax.swing.JLabel();
        lbl_fechaInicial = new javax.swing.JLabel();
        lbl_fechaFinal = new javax.swing.JLabel();
        cld_fechaInicial = new com.toedter.calendar.JDateChooser();
        cld_fechaFinal = new com.toedter.calendar.JDateChooser();
        btn_agregarPeriodo = new javax.swing.JButton();
        cbo_periodo = new javax.swing.JComboBox<>();
        btn_actualizar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_periodo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_periodo.setText("Período:");

        lbl_fechaInicial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_fechaInicial.setText("Fecha inicial:");

        lbl_fechaFinal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_fechaFinal.setText("Fecha final:");

        btn_agregarPeriodo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_agregarPeriodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botton_Guardar.png"))); // NOI18N
        btn_agregarPeriodo.setText("Guardar");
        btn_agregarPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarPeriodoActionPerformed(evt);
            }
        });

        cbo_periodo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbo_periodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un Periodo" }));

        btn_actualizar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botton_Actualizar.png"))); // NOI18N
        btn_actualizar.setText("Actualizar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        jButton2.setText("jButton1");

        jPanel2.setBackground(new java.awt.Color(215, 236, 233));

        jPanel3.setBackground(new java.awt.Color(232, 251, 249));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Período Histórico");
        jPanel3.add(jLabel1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagen 3.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu.png"))); // NOI18N
        jMenu1.setText("Menú");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(lbl_fechaFinal)
                .addGap(70, 70, 70)
                .addComponent(cld_fechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(btn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(580, 580, 580)
                .addComponent(cld_fechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(lbl_fechaInicial))
            .addGroup(layout.createSequentialGroup()
                .addGap(580, 580, 580)
                .addComponent(cbo_periodo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(btn_agregarPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addComponent(lbl_periodo))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_fechaFinal)
                    .addComponent(cld_fechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(btn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(cld_fechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(lbl_fechaInicial))
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(cbo_periodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(btn_agregarPeriodo))
            .addGroup(layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(lbl_periodo))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarPeriodoActionPerformed
        String nombre,periodo;
        periodo=cbo_periodo.getSelectedItem().toString().substring(0,1);
        Date dateinicial = cld_fechaInicial.getDate();
        Date datefinal = cld_fechaFinal.getDate();

        int mes = cld_fechaInicial.getDate().getMonth() + 1;
        int año = cld_fechaInicial.getDate().getYear() +1900;
        int dia =cld_fechaInicial.getDate().getDate();
        String fecha = año + "-" + mes +"-"+ dia;

        int mes2 = cld_fechaFinal.getDate().getMonth() + 1;
        int año2 = cld_fechaFinal.getDate().getYear() +1900;
        int dia2 =cld_fechaFinal.getDate().getDate();
        String fecha2 = año2 + "-" + mes2 +"-"+ dia2;

        nombre=año+"-"+periodo;
 JOptionPane.showMessageDialog(null, "Se ha guardado el periodo: "+nombre+periodo);
        try{
            PreparedStatement ps;
            ResultSet rs;
            ps=con.prepareStatement("insert into Periodo_historico(fecha_final,fecha_inicial,id_periodo,nombre_periodo_historico)"
                + "             VALUES(?,?,?,?)");

            ps.setString(1, fecha2);
            ps.setString(2, fecha);
            ps.setString(3, periodo);
            ps.setString(4, nombre);


            int res= ps.executeUpdate();
            if(res > 0){
                JOptionPane.showMessageDialog(null, "Se ha guardado el periodo: "+nombre);
                // limpiar();
            }else {
                JOptionPane.showMessageDialog(null, "Error al Guardar la información");
            }

        } catch ( Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_agregarPeriodoActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
     if ((cbo_periodo.getSelectedItem().equals("Seleccione una Periodo")||  (cld_fechaInicial.getDate()== null) ||  (cld_fechaFinal.getDate()== null))) {
            JOptionPane.showMessageDialog(this, "¡Debe rellenar todos los campos!");
        }

       else if (JOptionPane.showConfirmDialog(null, "¿Está seguro que desea actualizar el periodo ?", "Confirmación de actualización", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE
        ) == JOptionPane.YES_OPTION) {
            String nombre,periodo;
        periodo=cbo_periodo.getSelectedItem().toString().substring(0,1);
        Date dateinicial = cld_fechaInicial.getDate();
        Date datefinal = cld_fechaFinal.getDate();

        int mes = cld_fechaInicial.getDate().getMonth() + 1;
        int año = cld_fechaInicial.getDate().getYear() +1900;
        int dia =cld_fechaInicial.getDate().getDate();
        String fecha = año + "-" + mes +"-"+ dia;

        int mes2 = cld_fechaFinal.getDate().getMonth() + 1;
        int año2 = cld_fechaFinal.getDate().getYear() +1900;
        int dia2 =cld_fechaFinal.getDate().getDate();
        String fecha2 = año2 + "-" + mes2 +"-"+ dia2;

        nombre=año+"-"+periodo;
            try {
                PreparedStatement ps;
                ResultSet rs;
                ps = con.prepareStatement("update Periodo_historico set\n" +
                                            "id_periodo=?,\n" +
                                            "fecha_inicial=?,\n" +
                                            "fecha_final=?,\n" +
                                            "nombre_periodo_historico=?\n" +
                                            "where id_periodo_historico= 4");
              
                ps.setString(1,periodo);
                ps.setString(2,fecha);
                ps.setString(3,fecha2);
                ps.setString(4,nombre);
                int res = ps.executeUpdate();
                
                 if(res > 0){
                JOptionPane.showMessageDialog(null, "Se ha Actualizado el periodo: "+nombre);
                // limpiar();
            }else {
                JOptionPane.showMessageDialog(null, "Error al Actualizar la información");
            }
                
            } catch (Exception e) {
                System.out.println(e);
            }
          
        }
        
    }//GEN-LAST:event_btn_actualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeriodoHis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeriodoHis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeriodoHis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeriodoHis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PeriodoHis().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(PeriodoHis.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_agregarPeriodo;
    private javax.swing.JComboBox<String> cbo_periodo;
    private com.toedter.calendar.JDateChooser cld_fechaFinal;
    private com.toedter.calendar.JDateChooser cld_fechaInicial;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_fechaFinal;
    private javax.swing.JLabel lbl_fechaInicial;
    private javax.swing.JLabel lbl_periodo;
    // End of variables declaration//GEN-END:variables
}
