/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_registro;

import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class Secciones extends javax.swing.JFrame {

    /**
     * Creates new form Secciones
     */
    public Secciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_horaFinal = new javax.swing.JLabel();
        txt_nombreSeccion = new javax.swing.JTextField();
        txt_codigoAsignatura = new javax.swing.JTextField();
        txt_horaInicial = new javax.swing.JTextField();
        txt_horaFinal = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        lbl_nombreSeccion = new javax.swing.JLabel();
        lbl_codigoAsignaturas = new javax.swing.JLabel();
        lbl_horaInicial = new javax.swing.JLabel();
        btn_eliminar = new javax.swing.JButton();
        lbl_aula = new javax.swing.JLabel();
        txt_aula = new javax.swing.JTextField();
        lbl_titulo = new javax.swing.JLabel();
        cbo_lunes = new javax.swing.JCheckBox();
        cbo_martes = new javax.swing.JCheckBox();
        cbo_miercoles = new javax.swing.JCheckBox();
        cbo_jueves = new javax.swing.JCheckBox();
        cbo_viernes = new javax.swing.JCheckBox();
        cbo_sabado = new javax.swing.JCheckBox();
        cbo_domingo = new javax.swing.JCheckBox();
        lbl_dias = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_horaFinal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_horaFinal.setText("Hora final:");

        txt_nombreSeccion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txt_codigoAsignatura.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txt_horaInicial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txt_horaFinal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btn_guardar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_actualizar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_actualizar.setText("Actualizar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        lbl_nombreSeccion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_nombreSeccion.setText("Nombre sección:");

        lbl_codigoAsignaturas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_codigoAsignaturas.setText("Codigo asignatura:");

        lbl_horaInicial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_horaInicial.setText("Hora inicial:");

        btn_eliminar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        lbl_aula.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_aula.setText("Aula: ");

        txt_aula.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbl_titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_titulo.setText("Registro de sección");

        cbo_lunes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbo_lunes.setText("Lunes");

        cbo_martes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbo_martes.setText("Martes");

        cbo_miercoles.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbo_miercoles.setText("Miércoles");

        cbo_jueves.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbo_jueves.setText("Jueves");

        cbo_viernes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbo_viernes.setText("Viernes");

        cbo_sabado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbo_sabado.setText("Sábado");

        cbo_domingo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbo_domingo.setText("Domingo");

        lbl_dias.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_dias.setText("Dias de la asignatura");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_titulo)
                        .addGap(383, 383, 383))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addComponent(btn_guardar)
                                .addGap(18, 18, 18)
                                .addComponent(btn_actualizar)
                                .addGap(18, 18, 18)
                                .addComponent(btn_eliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbl_codigoAsignaturas)
                                            .addComponent(lbl_nombreSeccion))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txt_codigoAsignatura, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_nombreSeccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(45, 45, 45)
                                            .addComponent(lbl_aula)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_aula))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbl_horaInicial)
                                                .addComponent(lbl_horaFinal, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txt_horaInicial)
                                                .addComponent(txt_horaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(274, 274, 274))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(298, 298, 298)
                                    .addComponent(lbl_dias))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cbo_lunes)
                                    .addGap(39, 39, 39)
                                    .addComponent(cbo_martes)
                                    .addGap(39, 39, 39)
                                    .addComponent(cbo_miercoles)
                                    .addGap(29, 29, 29)
                                    .addComponent(cbo_jueves)
                                    .addGap(31, 31, 31)
                                    .addComponent(cbo_viernes)
                                    .addGap(35, 35, 35)
                                    .addComponent(cbo_sabado)
                                    .addGap(29, 29, 29)
                                    .addComponent(cbo_domingo))))
                        .addGap(60, 60, 60))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lbl_titulo)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombreSeccion)
                    .addComponent(txt_nombreSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_codigoAsignaturas)
                    .addComponent(txt_codigoAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_horaInicial)
                    .addComponent(txt_horaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_horaFinal)
                    .addComponent(txt_horaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_aula)
                    .addComponent(txt_aula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(lbl_dias)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_lunes)
                    .addComponent(cbo_martes)
                    .addComponent(cbo_miercoles)
                    .addComponent(cbo_jueves)
                    .addComponent(cbo_viernes)
                    .addComponent(cbo_sabado)
                    .addComponent(cbo_domingo))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
     String dias ="";
     
     if(cbo_lunes.isSelected()){
         dias = dias+ "Lu";
     }
     
     if(cbo_martes.isSelected()){
         dias = dias+ "Ma";
     }
     
     if(cbo_miercoles.isSelected()){
         dias = dias+ "Mie";
     }
     
     
     JOptionPane.showMessageDialog(null, dias);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Secciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Secciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Secciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Secciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Secciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JCheckBox cbo_domingo;
    private javax.swing.JCheckBox cbo_jueves;
    private javax.swing.JCheckBox cbo_lunes;
    private javax.swing.JCheckBox cbo_martes;
    private javax.swing.JCheckBox cbo_miercoles;
    private javax.swing.JCheckBox cbo_sabado;
    private javax.swing.JCheckBox cbo_viernes;
    private javax.swing.JLabel lbl_aula;
    private javax.swing.JLabel lbl_codigoAsignaturas;
    private javax.swing.JLabel lbl_dias;
    private javax.swing.JLabel lbl_horaFinal;
    private javax.swing.JLabel lbl_horaInicial;
    private javax.swing.JLabel lbl_nombreSeccion;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JTextField txt_aula;
    private javax.swing.JTextField txt_codigoAsignatura;
    private javax.swing.JTextField txt_horaFinal;
    private javax.swing.JTextField txt_horaInicial;
    private javax.swing.JTextField txt_nombreSeccion;
    // End of variables declaration//GEN-END:variables
}
